//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace SAP.WebServices
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "MasterDataSoap", Namespace = "http://electra-ai.com/")]
    public partial class MasterData : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetBusinessPartnerOperationCompleted;

        private System.Threading.SendOrPostCallback GetItemMasterDataOperationCompleted;

        private System.Threading.SendOrPostCallback GetWarehouseOperationCompleted;

        private System.Threading.SendOrPostCallback GetTaxGroupOperationCompleted;

        /// <remarks/>
        public MasterData()
        {
            this.Url = "http://demo1.w4vn.com/MasterData.asmx";
        }

        /// <remarks/>
        public event GetBusinessPartnerCompletedEventHandler GetBusinessPartnerCompleted;

        /// <remarks/>
        public event GetItemMasterDataCompletedEventHandler GetItemMasterDataCompleted;

        /// <remarks/>
        public event GetWarehouseCompletedEventHandler GetWarehouseCompleted;

        /// <remarks/>
        public event GetTaxGroupCompletedEventHandler GetTaxGroupCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://electra-ai.com/GetBusinessPartner", RequestNamespace = "http://electra-ai.com/", ResponseNamespace = "http://electra-ai.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetBusinessPartner()
        {
            object[] results = this.Invoke("GetBusinessPartner", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetBusinessPartner(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetBusinessPartner", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetBusinessPartner(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetBusinessPartnerAsync()
        {
            this.GetBusinessPartnerAsync(null);
        }

        /// <remarks/>
        public void GetBusinessPartnerAsync(object userState)
        {
            if ((this.GetBusinessPartnerOperationCompleted == null))
            {
                this.GetBusinessPartnerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBusinessPartnerOperationCompleted);
            }
            this.InvokeAsync("GetBusinessPartner", new object[0], this.GetBusinessPartnerOperationCompleted, userState);
        }

        private void OnGetBusinessPartnerOperationCompleted(object arg)
        {
            if ((this.GetBusinessPartnerCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBusinessPartnerCompleted(this, new GetBusinessPartnerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://electra-ai.com/GetItemMasterData", RequestNamespace = "http://electra-ai.com/", ResponseNamespace = "http://electra-ai.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetItemMasterData()
        {
            object[] results = this.Invoke("GetItemMasterData", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetItemMasterData(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetItemMasterData", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetItemMasterData(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetItemMasterDataAsync()
        {
            this.GetItemMasterDataAsync(null);
        }

        /// <remarks/>
        public void GetItemMasterDataAsync(object userState)
        {
            if ((this.GetItemMasterDataOperationCompleted == null))
            {
                this.GetItemMasterDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemMasterDataOperationCompleted);
            }
            this.InvokeAsync("GetItemMasterData", new object[0], this.GetItemMasterDataOperationCompleted, userState);
        }

        private void OnGetItemMasterDataOperationCompleted(object arg)
        {
            if ((this.GetItemMasterDataCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemMasterDataCompleted(this, new GetItemMasterDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://electra-ai.com/GetWarehouse", RequestNamespace = "http://electra-ai.com/", ResponseNamespace = "http://electra-ai.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetWarehouse()
        {
            object[] results = this.Invoke("GetWarehouse", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetWarehouse(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetWarehouse", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetWarehouse(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetWarehouseAsync()
        {
            this.GetWarehouseAsync(null);
        }

        /// <remarks/>
        public void GetWarehouseAsync(object userState)
        {
            if ((this.GetWarehouseOperationCompleted == null))
            {
                this.GetWarehouseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWarehouseOperationCompleted);
            }
            this.InvokeAsync("GetWarehouse", new object[0], this.GetWarehouseOperationCompleted, userState);
        }

        private void OnGetWarehouseOperationCompleted(object arg)
        {
            if ((this.GetWarehouseCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWarehouseCompleted(this, new GetWarehouseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://electra-ai.com/GetTaxGroup", RequestNamespace = "http://electra-ai.com/", ResponseNamespace = "http://electra-ai.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTaxGroup(string Category)
        {
            object[] results = this.Invoke("GetTaxGroup", new object[] {
                    Category});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetTaxGroup(string Category, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetTaxGroup", new object[] {
                    Category}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetTaxGroup(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetTaxGroupAsync(string Category)
        {
            this.GetTaxGroupAsync(Category, null);
        }

        /// <remarks/>
        public void GetTaxGroupAsync(string Category, object userState)
        {
            if ((this.GetTaxGroupOperationCompleted == null))
            {
                this.GetTaxGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTaxGroupOperationCompleted);
            }
            this.InvokeAsync("GetTaxGroup", new object[] {
                    Category}, this.GetTaxGroupOperationCompleted, userState);
        }

        private void OnGetTaxGroupOperationCompleted(object arg)
        {
            if ((this.GetTaxGroupCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTaxGroupCompleted(this, new GetTaxGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetBusinessPartnerCompletedEventHandler(object sender, GetBusinessPartnerCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBusinessPartnerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetBusinessPartnerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetItemMasterDataCompletedEventHandler(object sender, GetItemMasterDataCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemMasterDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetItemMasterDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetWarehouseCompletedEventHandler(object sender, GetWarehouseCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWarehouseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetWarehouseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetTaxGroupCompletedEventHandler(object sender, GetTaxGroupCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTaxGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetTaxGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}
