//------------------------------------------------------------------------------
// <auto-generated>
//     This _PrjCode was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the _PrjCode is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source _PrjCode was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace SAP.WebServices
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "TransactionSoap", Namespace = "http://tempuri.org/")]
    public partial class Transaction : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback CreateMarketingDocumentOperationCompleted;

        /// <remarks/>
        public Transaction()
        {
            String urlSetting = System.Configuration.ConfigurationManager.AppSettings["TransactionWSURL"];
            if (String.IsNullOrEmpty(urlSetting))
                this.Url = "http://localhost:49881/Transaction.asmx";
            else
                this.Url = urlSetting;
        }

        /// <remarks/>
        public event CreateMarketingDocumentCompletedEventHandler CreateMarketingDocumentCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateMarketingDocument", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateMarketingDocument(string strXml)
        {
            object[] results = this.Invoke("CreateMarketingDocument", new object[] {
                    strXml});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreateMarketingDocument(string strXml, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CreateMarketingDocument", new object[] {
                    strXml}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCreateMarketingDocument(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CreateMarketingDocumentAsync(string strXml)
        {
            this.CreateMarketingDocumentAsync(strXml, null);
        }

        /// <remarks/>
        public void CreateMarketingDocumentAsync(string strXml, object userState)
        {
            if ((this.CreateMarketingDocumentOperationCompleted == null))
            {
                this.CreateMarketingDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMarketingDocumentOperationCompleted);
            }
            this.InvokeAsync("CreateMarketingDocument", new object[] {
                    strXml}, this.CreateMarketingDocumentOperationCompleted, userState);
        }

        private void OnCreateMarketingDocumentOperationCompleted(object arg)
        {
            if ((this.CreateMarketingDocumentCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMarketingDocumentCompleted(this, new CreateMarketingDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void CreateMarketingDocumentCompletedEventHandler(object sender, CreateMarketingDocumentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMarketingDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CreateMarketingDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

}