//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace SAP.WebServices
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "TransactionSoap", Namespace = "http://tempuri.org/")]
    public partial class Transaction : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback CreateMarketingDocumentOperationCompleted;

        private System.Threading.SendOrPostCallback GetMarketingDocumentOperationCompleted;

        private System.Threading.SendOrPostCallback GetSalesOpportunityOperationCompleted;

        private System.Threading.SendOrPostCallback Insert_Promotion_TransferOperationCompleted;

        private System.Threading.SendOrPostCallback CreateOpportunityOperationCompleted;

        /// <remarks/>
        public Transaction()
        {
            String urlSetting = System.Configuration.ConfigurationManager.AppSettings["TransactionWSURL"];
            if (String.IsNullOrEmpty(urlSetting))
                this.Url = "http://localhost:49881/Transaction.asmx";
            else
                this.Url = urlSetting;
        }

        /// <remarks/>
        public event CreateMarketingDocumentCompletedEventHandler CreateMarketingDocumentCompleted;

        /// <remarks/>
        public event GetMarketingDocumentCompletedEventHandler GetMarketingDocumentCompleted;

        /// <remarks/>
        public event GetSalesOpportunityCompletedEventHandler GetSalesOpportunityCompleted;

        /// <remarks/>
        public event Insert_Promotion_TransferCompletedEventHandler Insert_Promotion_TransferCompleted;

        /// <remarks/>
        public event CreateOpportunityCompletedEventHandler CreateOpportunityCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateMarketingDocument", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CreateMarketingDocument(string strXml)
        {
            object[] results = this.Invoke("CreateMarketingDocument", new object[] {
                    strXml});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreateMarketingDocument(string strXml, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CreateMarketingDocument", new object[] {
                    strXml}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndCreateMarketingDocument(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void CreateMarketingDocumentAsync(string strXml)
        {
            this.CreateMarketingDocumentAsync(strXml, null);
        }

        /// <remarks/>
        public void CreateMarketingDocumentAsync(string strXml, object userState)
        {
            if ((this.CreateMarketingDocumentOperationCompleted == null))
            {
                this.CreateMarketingDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMarketingDocumentOperationCompleted);
            }
            this.InvokeAsync("CreateMarketingDocument", new object[] {
                    strXml}, this.CreateMarketingDocumentOperationCompleted, userState);
        }

        private void OnCreateMarketingDocumentOperationCompleted(object arg)
        {
            if ((this.CreateMarketingDocumentCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMarketingDocumentCompleted(this, new CreateMarketingDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMarketingDocument", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMarketingDocument(string DocType, int DocEntry, string UserID)
        {
            object[] results = this.Invoke("GetMarketingDocument", new object[] {
                    DocType,
                    DocEntry,
                    UserID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetMarketingDocument(string DocType, int DocEntry, string UserID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetMarketingDocument", new object[] {
                    DocType,
                    DocEntry,
                    UserID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetMarketingDocument(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetMarketingDocumentAsync(string DocType, int DocEntry, string UserID)
        {
            this.GetMarketingDocumentAsync(DocType, DocEntry, UserID, null);
        }

        /// <remarks/>
        public void GetMarketingDocumentAsync(string DocType, int DocEntry, string UserID, object userState)
        {
            if ((this.GetMarketingDocumentOperationCompleted == null))
            {
                this.GetMarketingDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMarketingDocumentOperationCompleted);
            }
            this.InvokeAsync("GetMarketingDocument", new object[] {
                    DocType,
                    DocEntry,
                    UserID}, this.GetMarketingDocumentOperationCompleted, userState);
        }

        private void OnGetMarketingDocumentOperationCompleted(object arg)
        {
            if ((this.GetMarketingDocumentCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMarketingDocumentCompleted(this, new GetMarketingDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSalesOpportunity", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSalesOpportunity(int OpprId, string UserID)
        {
            object[] results = this.Invoke("GetSalesOpportunity", new object[] {
                    OpprId,
                    UserID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetSalesOpportunity(int OpprId, string UserID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetSalesOpportunity", new object[] {
                    OpprId,
                    UserID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetSalesOpportunity(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetSalesOpportunityAsync(int OpprId, string UserID)
        {
            this.GetSalesOpportunityAsync(OpprId, UserID, null);
        }

        /// <remarks/>
        public void GetSalesOpportunityAsync(int OpprId, string UserID, object userState)
        {
            if ((this.GetSalesOpportunityOperationCompleted == null))
            {
                this.GetSalesOpportunityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesOpportunityOperationCompleted);
            }
            this.InvokeAsync("GetSalesOpportunity", new object[] {
                    OpprId,
                    UserID}, this.GetSalesOpportunityOperationCompleted, userState);
        }

        private void OnGetSalesOpportunityOperationCompleted(object arg)
        {
            if ((this.GetSalesOpportunityCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesOpportunityCompleted(this, new GetSalesOpportunityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_Promotion_Transfer", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insert_Promotion_Transfer(string ItemCode, string CardCode, int Qty)
        {
            object[] results = this.Invoke("Insert_Promotion_Transfer", new object[] {
                    ItemCode,
                    CardCode,
                    Qty});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginInsert_Promotion_Transfer(string ItemCode, string CardCode, int Qty, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Insert_Promotion_Transfer", new object[] {
                    ItemCode,
                    CardCode,
                    Qty}, callback, asyncState);
        }

        /// <remarks/>
        public string EndInsert_Promotion_Transfer(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void Insert_Promotion_TransferAsync(string ItemCode, string CardCode, int Qty)
        {
            this.Insert_Promotion_TransferAsync(ItemCode, CardCode, Qty, null);
        }

        /// <remarks/>
        public void Insert_Promotion_TransferAsync(string ItemCode, string CardCode, int Qty, object userState)
        {
            if ((this.Insert_Promotion_TransferOperationCompleted == null))
            {
                this.Insert_Promotion_TransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_Promotion_TransferOperationCompleted);
            }
            this.InvokeAsync("Insert_Promotion_Transfer", new object[] {
                    ItemCode,
                    CardCode,
                    Qty}, this.Insert_Promotion_TransferOperationCompleted, userState);
        }

        private void OnInsert_Promotion_TransferOperationCompleted(object arg)
        {
            if ((this.Insert_Promotion_TransferCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_Promotion_TransferCompleted(this, new Insert_Promotion_TransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOpportunity", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CreateOpportunity(string strXml)
        {
            object[] results = this.Invoke("CreateOpportunity", new object[] {
                    strXml});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreateOpportunity(string strXml, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CreateOpportunity", new object[] {
                    strXml}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndCreateOpportunity(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void CreateOpportunityAsync(string strXml)
        {
            this.CreateOpportunityAsync(strXml, null);
        }

        /// <remarks/>
        public void CreateOpportunityAsync(string strXml, object userState)
        {
            if ((this.CreateOpportunityOperationCompleted == null))
            {
                this.CreateOpportunityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOpportunityOperationCompleted);
            }
            this.InvokeAsync("CreateOpportunity", new object[] {
                    strXml}, this.CreateOpportunityOperationCompleted, userState);
        }

        private void OnCreateOpportunityOperationCompleted(object arg)
        {
            if ((this.CreateOpportunityCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOpportunityCompleted(this, new CreateOpportunityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void CreateMarketingDocumentCompletedEventHandler(object sender, CreateMarketingDocumentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMarketingDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CreateMarketingDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetMarketingDocumentCompletedEventHandler(object sender, GetMarketingDocumentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMarketingDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetMarketingDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetSalesOpportunityCompletedEventHandler(object sender, GetSalesOpportunityCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesOpportunityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetSalesOpportunityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void Insert_Promotion_TransferCompletedEventHandler(object sender, Insert_Promotion_TransferCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_Promotion_TransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal Insert_Promotion_TransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void CreateOpportunityCompletedEventHandler(object sender, CreateOpportunityCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOpportunityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CreateOpportunityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}