//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDefaultSoap")]
public interface GetDefaultSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultLineInfo", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet GetDefaultLineInfo(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultVendor", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetDefaultVendor(string UserID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultCustomer", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string GetDefaultCustomer(string UserID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPromotion", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet GetPromotion(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface GetDefaultSoapChannel : GetDefaultSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetDefaultSoapClient : System.ServiceModel.ClientBase<GetDefaultSoap>, GetDefaultSoap
{
    
    public GetDefaultSoapClient()
    {
    }
    
    public GetDefaultSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetDefaultSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetDefaultSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetDefaultSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Data.DataSet GetDefaultLineInfo(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate)
    {
        return base.Channel.GetDefaultLineInfo(UserID, cardCode, itemCode, Quantity, refDate);
    }
    
    public string GetDefaultVendor(string UserID)
    {
        return base.Channel.GetDefaultVendor(UserID);
    }
    
    public string GetDefaultCustomer(string UserID)
    {
        return base.Channel.GetDefaultCustomer(UserID);
    }
    
    public System.Data.DataSet GetPromotion(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount)
    {
        return base.Channel.GetPromotion(UserID, ItemCode, CardCode, Quantity, DocDate, Amount);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDefaultHttpGet")]
public interface GetDefaultHttpGet
{
    
    // CODEGEN: Generating message contract since the operation GetDefaultLineInfo is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultHttpGet/GetDefaultLineInfoRequest", ReplyAction="http://tempuri.org/GetDefaultHttpGet/GetDefaultLineInfoResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDefaultLineInfoResponse GetDefaultLineInfo(GetDefaultLineInfoRequest request);
    
    // CODEGEN: Generating message contract since the operation GetDefaultVendor is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultHttpGet/GetDefaultVendorRequest", ReplyAction="http://tempuri.org/GetDefaultHttpGet/GetDefaultVendorResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDefaultVendorResponse GetDefaultVendor(GetDefaultVendorRequest request);
    
    // CODEGEN: Generating message contract since the operation GetDefaultCustomer is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultHttpGet/GetDefaultCustomerRequest", ReplyAction="http://tempuri.org/GetDefaultHttpGet/GetDefaultCustomerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDefaultCustomerResponse GetDefaultCustomer(GetDefaultCustomerRequest request);
    
    // CODEGEN: Generating message contract since the operation GetPromotion is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultHttpGet/GetPromotionRequest", ReplyAction="http://tempuri.org/GetDefaultHttpGet/GetPromotionResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetPromotionResponse GetPromotion(GetPromotionRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultLineInfoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string cardCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string itemCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string Quantity;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string refDate;
    
    public GetDefaultLineInfoRequest()
    {
    }
    
    public GetDefaultLineInfoRequest(string UserID, string cardCode, string itemCode, string Quantity, string refDate)
    {
        this.UserID = UserID;
        this.cardCode = cardCode;
        this.itemCode = itemCode;
        this.Quantity = Quantity;
        this.refDate = refDate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultLineInfoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataSet DataSet;
    
    public GetDefaultLineInfoResponse()
    {
    }
    
    public GetDefaultLineInfoResponse(System.Data.DataSet DataSet)
    {
        this.DataSet = DataSet;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultVendorRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserID;
    
    public GetDefaultVendorRequest()
    {
    }
    
    public GetDefaultVendorRequest(string UserID)
    {
        this.UserID = UserID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultVendorResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string @string;
    
    public GetDefaultVendorResponse()
    {
    }
    
    public GetDefaultVendorResponse(string @string)
    {
        this.@string = @string;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultCustomerRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserID;
    
    public GetDefaultCustomerRequest()
    {
    }
    
    public GetDefaultCustomerRequest(string UserID)
    {
        this.UserID = UserID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultCustomerResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string @string;
    
    public GetDefaultCustomerResponse()
    {
    }
    
    public GetDefaultCustomerResponse(string @string)
    {
        this.@string = @string;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetPromotionRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ItemCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string CardCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string Quantity;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string DocDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string Amount;
    
    public GetPromotionRequest()
    {
    }
    
    public GetPromotionRequest(string UserID, string ItemCode, string CardCode, string Quantity, string DocDate, string Amount)
    {
        this.UserID = UserID;
        this.ItemCode = ItemCode;
        this.CardCode = CardCode;
        this.Quantity = Quantity;
        this.DocDate = DocDate;
        this.Amount = Amount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetPromotionResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataSet DataSet;
    
    public GetPromotionResponse()
    {
    }
    
    public GetPromotionResponse(System.Data.DataSet DataSet)
    {
        this.DataSet = DataSet;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface GetDefaultHttpGetChannel : GetDefaultHttpGet, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetDefaultHttpGetClient : System.ServiceModel.ClientBase<GetDefaultHttpGet>, GetDefaultHttpGet
{
    
    public GetDefaultHttpGetClient()
    {
    }
    
    public GetDefaultHttpGetClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetDefaultHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetDefaultHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetDefaultHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDefaultLineInfoResponse GetDefaultHttpGet.GetDefaultLineInfo(GetDefaultLineInfoRequest request)
    {
        return base.Channel.GetDefaultLineInfo(request);
    }
    
    public System.Data.DataSet GetDefaultLineInfo(string UserID, string cardCode, string itemCode, string Quantity, string refDate)
    {
        GetDefaultLineInfoRequest inValue = new GetDefaultLineInfoRequest();
        inValue.UserID = UserID;
        inValue.cardCode = cardCode;
        inValue.itemCode = itemCode;
        inValue.Quantity = Quantity;
        inValue.refDate = refDate;
        GetDefaultLineInfoResponse retVal = ((GetDefaultHttpGet)(this)).GetDefaultLineInfo(inValue);
        return retVal.DataSet;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDefaultVendorResponse GetDefaultHttpGet.GetDefaultVendor(GetDefaultVendorRequest request)
    {
        return base.Channel.GetDefaultVendor(request);
    }
    
    public string GetDefaultVendor(string UserID)
    {
        GetDefaultVendorRequest inValue = new GetDefaultVendorRequest();
        inValue.UserID = UserID;
        GetDefaultVendorResponse retVal = ((GetDefaultHttpGet)(this)).GetDefaultVendor(inValue);
        return retVal.@string;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDefaultCustomerResponse GetDefaultHttpGet.GetDefaultCustomer(GetDefaultCustomerRequest request)
    {
        return base.Channel.GetDefaultCustomer(request);
    }
    
    public string GetDefaultCustomer(string UserID)
    {
        GetDefaultCustomerRequest inValue = new GetDefaultCustomerRequest();
        inValue.UserID = UserID;
        GetDefaultCustomerResponse retVal = ((GetDefaultHttpGet)(this)).GetDefaultCustomer(inValue);
        return retVal.@string;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetPromotionResponse GetDefaultHttpGet.GetPromotion(GetPromotionRequest request)
    {
        return base.Channel.GetPromotion(request);
    }
    
    public System.Data.DataSet GetPromotion(string UserID, string ItemCode, string CardCode, string Quantity, string DocDate, string Amount)
    {
        GetPromotionRequest inValue = new GetPromotionRequest();
        inValue.UserID = UserID;
        inValue.ItemCode = ItemCode;
        inValue.CardCode = CardCode;
        inValue.Quantity = Quantity;
        inValue.DocDate = DocDate;
        inValue.Amount = Amount;
        GetPromotionResponse retVal = ((GetDefaultHttpGet)(this)).GetPromotion(inValue);
        return retVal.DataSet;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDefaultHttpPost")]
public interface GetDefaultHttpPost
{
    
    // CODEGEN: Generating message contract since the operation GetDefaultLineInfo is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultHttpPost/GetDefaultLineInfoRequest", ReplyAction="http://tempuri.org/GetDefaultHttpPost/GetDefaultLineInfoResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDefaultLineInfoResponse1 GetDefaultLineInfo(GetDefaultLineInfoRequest1 request);
    
    // CODEGEN: Generating message contract since the operation GetDefaultVendor is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultHttpPost/GetDefaultVendorRequest", ReplyAction="http://tempuri.org/GetDefaultHttpPost/GetDefaultVendorResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDefaultVendorResponse1 GetDefaultVendor(GetDefaultVendorRequest1 request);
    
    // CODEGEN: Generating message contract since the operation GetDefaultCustomer is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultHttpPost/GetDefaultCustomerRequest", ReplyAction="http://tempuri.org/GetDefaultHttpPost/GetDefaultCustomerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDefaultCustomerResponse1 GetDefaultCustomer(GetDefaultCustomerRequest1 request);
    
    // CODEGEN: Generating message contract since the operation GetPromotion is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDefaultHttpPost/GetPromotionRequest", ReplyAction="http://tempuri.org/GetDefaultHttpPost/GetPromotionResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetPromotionResponse1 GetPromotion(GetPromotionRequest1 request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultLineInfoRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string cardCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string itemCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string Quantity;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string refDate;
    
    public GetDefaultLineInfoRequest1()
    {
    }
    
    public GetDefaultLineInfoRequest1(string UserID, string cardCode, string itemCode, string Quantity, string refDate)
    {
        this.UserID = UserID;
        this.cardCode = cardCode;
        this.itemCode = itemCode;
        this.Quantity = Quantity;
        this.refDate = refDate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultLineInfoResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataSet DataSet;
    
    public GetDefaultLineInfoResponse1()
    {
    }
    
    public GetDefaultLineInfoResponse1(System.Data.DataSet DataSet)
    {
        this.DataSet = DataSet;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultVendorRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserID;
    
    public GetDefaultVendorRequest1()
    {
    }
    
    public GetDefaultVendorRequest1(string UserID)
    {
        this.UserID = UserID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultVendorResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string @string;
    
    public GetDefaultVendorResponse1()
    {
    }
    
    public GetDefaultVendorResponse1(string @string)
    {
        this.@string = @string;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultCustomerRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserID;
    
    public GetDefaultCustomerRequest1()
    {
    }
    
    public GetDefaultCustomerRequest1(string UserID)
    {
        this.UserID = UserID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetDefaultCustomerResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string @string;
    
    public GetDefaultCustomerResponse1()
    {
    }
    
    public GetDefaultCustomerResponse1(string @string)
    {
        this.@string = @string;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetPromotionRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string UserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
    public string ItemCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
    public string CardCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
    public string Quantity;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
    public string DocDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
    public string Amount;
    
    public GetPromotionRequest1()
    {
    }
    
    public GetPromotionRequest1(string UserID, string ItemCode, string CardCode, string Quantity, string DocDate, string Amount)
    {
        this.UserID = UserID;
        this.ItemCode = ItemCode;
        this.CardCode = CardCode;
        this.Quantity = Quantity;
        this.DocDate = DocDate;
        this.Amount = Amount;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetPromotionResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Data.DataSet DataSet;
    
    public GetPromotionResponse1()
    {
    }
    
    public GetPromotionResponse1(System.Data.DataSet DataSet)
    {
        this.DataSet = DataSet;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface GetDefaultHttpPostChannel : GetDefaultHttpPost, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetDefaultHttpPostClient : System.ServiceModel.ClientBase<GetDefaultHttpPost>, GetDefaultHttpPost
{
    
    public GetDefaultHttpPostClient()
    {
    }
    
    public GetDefaultHttpPostClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetDefaultHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetDefaultHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetDefaultHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDefaultLineInfoResponse1 GetDefaultHttpPost.GetDefaultLineInfo(GetDefaultLineInfoRequest1 request)
    {
        return base.Channel.GetDefaultLineInfo(request);
    }
    
    public System.Data.DataSet GetDefaultLineInfo(string UserID, string cardCode, string itemCode, string Quantity, string refDate)
    {
        GetDefaultLineInfoRequest1 inValue = new GetDefaultLineInfoRequest1();
        inValue.UserID = UserID;
        inValue.cardCode = cardCode;
        inValue.itemCode = itemCode;
        inValue.Quantity = Quantity;
        inValue.refDate = refDate;
        GetDefaultLineInfoResponse1 retVal = ((GetDefaultHttpPost)(this)).GetDefaultLineInfo(inValue);
        return retVal.DataSet;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDefaultVendorResponse1 GetDefaultHttpPost.GetDefaultVendor(GetDefaultVendorRequest1 request)
    {
        return base.Channel.GetDefaultVendor(request);
    }
    
    public string GetDefaultVendor(string UserID)
    {
        GetDefaultVendorRequest1 inValue = new GetDefaultVendorRequest1();
        inValue.UserID = UserID;
        GetDefaultVendorResponse1 retVal = ((GetDefaultHttpPost)(this)).GetDefaultVendor(inValue);
        return retVal.@string;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDefaultCustomerResponse1 GetDefaultHttpPost.GetDefaultCustomer(GetDefaultCustomerRequest1 request)
    {
        return base.Channel.GetDefaultCustomer(request);
    }
    
    public string GetDefaultCustomer(string UserID)
    {
        GetDefaultCustomerRequest1 inValue = new GetDefaultCustomerRequest1();
        inValue.UserID = UserID;
        GetDefaultCustomerResponse1 retVal = ((GetDefaultHttpPost)(this)).GetDefaultCustomer(inValue);
        return retVal.@string;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetPromotionResponse1 GetDefaultHttpPost.GetPromotion(GetPromotionRequest1 request)
    {
        return base.Channel.GetPromotion(request);
    }
    
    public System.Data.DataSet GetPromotion(string UserID, string ItemCode, string CardCode, string Quantity, string DocDate, string Amount)
    {
        GetPromotionRequest1 inValue = new GetPromotionRequest1();
        inValue.UserID = UserID;
        inValue.ItemCode = ItemCode;
        inValue.CardCode = CardCode;
        inValue.Quantity = Quantity;
        inValue.DocDate = DocDate;
        inValue.Amount = Amount;
        GetPromotionResponse1 retVal = ((GetDefaultHttpPost)(this)).GetPromotion(inValue);
        return retVal.DataSet;
    }
}
