//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


namespace SAP
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GetDefaultSoap", Namespace = "http://tempuri.org/")]
    public partial class GetDefault : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetDefaultLineInfoOperationCompleted;

        private System.Threading.SendOrPostCallback GetDefaultVendorOperationCompleted;

        private System.Threading.SendOrPostCallback GetDefaultCustomerOperationCompleted;

        private System.Threading.SendOrPostCallback GetPromotionOperationCompleted;

        /// <remarks/>
        public GetDefault()
        {
            String urlSetting = System.Configuration.ConfigurationManager.AppSettings["GetDefaultWSURL"];
            if (String.IsNullOrEmpty(urlSetting))
                this.Url = "http://demo1.w4vn.com/GetDefault.asmx";
            else
                this.Url = urlSetting;
        }

        /// <remarks/>
        public event GetDefaultLineInfoCompletedEventHandler GetDefaultLineInfoCompleted;

        /// <remarks/>
        public event GetDefaultVendorCompletedEventHandler GetDefaultVendorCompleted;

        /// <remarks/>
        public event GetDefaultCustomerCompletedEventHandler GetDefaultCustomerCompleted;

        /// <remarks/>
        public event GetPromotionCompletedEventHandler GetPromotionCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDefaultLineInfo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDefaultLineInfo(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate)
        {
            object[] results = this.Invoke("GetDefaultLineInfo", new object[] {
                    UserID,
                    cardCode,
                    itemCode,
                    Quantity,
                    refDate});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDefaultLineInfo(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDefaultLineInfo", new object[] {
                    UserID,
                    cardCode,
                    itemCode,
                    Quantity,
                    refDate}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetDefaultLineInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetDefaultLineInfoAsync(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate)
        {
            this.GetDefaultLineInfoAsync(UserID, cardCode, itemCode, Quantity, refDate, null);
        }

        /// <remarks/>
        public void GetDefaultLineInfoAsync(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate, object userState)
        {
            if ((this.GetDefaultLineInfoOperationCompleted == null))
            {
                this.GetDefaultLineInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefaultLineInfoOperationCompleted);
            }
            this.InvokeAsync("GetDefaultLineInfo", new object[] {
                    UserID,
                    cardCode,
                    itemCode,
                    Quantity,
                    refDate}, this.GetDefaultLineInfoOperationCompleted, userState);
        }

        private void OnGetDefaultLineInfoOperationCompleted(object arg)
        {
            if ((this.GetDefaultLineInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefaultLineInfoCompleted(this, new GetDefaultLineInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDefaultVendor", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDefaultVendor(string UserID)
        {
            object[] results = this.Invoke("GetDefaultVendor", new object[] {
                    UserID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDefaultVendor(string UserID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDefaultVendor", new object[] {
                    UserID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetDefaultVendor(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetDefaultVendorAsync(string UserID)
        {
            this.GetDefaultVendorAsync(UserID, null);
        }

        /// <remarks/>
        public void GetDefaultVendorAsync(string UserID, object userState)
        {
            if ((this.GetDefaultVendorOperationCompleted == null))
            {
                this.GetDefaultVendorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefaultVendorOperationCompleted);
            }
            this.InvokeAsync("GetDefaultVendor", new object[] {
                    UserID}, this.GetDefaultVendorOperationCompleted, userState);
        }

        private void OnGetDefaultVendorOperationCompleted(object arg)
        {
            if ((this.GetDefaultVendorCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefaultVendorCompleted(this, new GetDefaultVendorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDefaultCustomer", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDefaultCustomer(string UserID)
        {
            object[] results = this.Invoke("GetDefaultCustomer", new object[] {
                    UserID});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDefaultCustomer(string UserID, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDefaultCustomer", new object[] {
                    UserID}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetDefaultCustomer(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetDefaultCustomerAsync(string UserID)
        {
            this.GetDefaultCustomerAsync(UserID, null);
        }

        /// <remarks/>
        public void GetDefaultCustomerAsync(string UserID, object userState)
        {
            if ((this.GetDefaultCustomerOperationCompleted == null))
            {
                this.GetDefaultCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefaultCustomerOperationCompleted);
            }
            this.InvokeAsync("GetDefaultCustomer", new object[] {
                    UserID}, this.GetDefaultCustomerOperationCompleted, userState);
        }

        private void OnGetDefaultCustomerOperationCompleted(object arg)
        {
            if ((this.GetDefaultCustomerCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefaultCustomerCompleted(this, new GetDefaultCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPromotion", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPromotion(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount)
        {
            object[] results = this.Invoke("GetPromotion", new object[] {
                    UserID,
                    ItemCode,
                    CardCode,
                    Quantity,
                    DocDate,
                    Amount});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPromotion(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPromotion", new object[] {
                    UserID,
                    ItemCode,
                    CardCode,
                    Quantity,
                    DocDate,
                    Amount}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetPromotion(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetPromotionAsync(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount)
        {
            this.GetPromotionAsync(UserID, ItemCode, CardCode, Quantity, DocDate, Amount, null);
        }

        /// <remarks/>
        public void GetPromotionAsync(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount, object userState)
        {
            if ((this.GetPromotionOperationCompleted == null))
            {
                this.GetPromotionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPromotionOperationCompleted);
            }
            this.InvokeAsync("GetPromotion", new object[] {
                    UserID,
                    ItemCode,
                    CardCode,
                    Quantity,
                    DocDate,
                    Amount}, this.GetPromotionOperationCompleted, userState);
        }

        private void OnGetPromotionOperationCompleted(object arg)
        {
            if ((this.GetPromotionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPromotionCompleted(this, new GetPromotionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDefaultLineInfoCompletedEventHandler(object sender, GetDefaultLineInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefaultLineInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDefaultLineInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDefaultVendorCompletedEventHandler(object sender, GetDefaultVendorCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefaultVendorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDefaultVendorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDefaultCustomerCompletedEventHandler(object sender, GetDefaultCustomerCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefaultCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDefaultCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetPromotionCompletedEventHandler(object sender, GetPromotionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPromotionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPromotionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}
