//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace SAP
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GetDefaultSoap", Namespace = "http://tempuri.org/")]
    public partial class GetDefault : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetDefaultLineInfoOperationCompleted;

        private System.Threading.SendOrPostCallback GetDefaultBPOperationCompleted;

        private System.Threading.SendOrPostCallback GetPromotionOperationCompleted;

        private System.Threading.SendOrPostCallback GetCopyFromToOperationCompleted;

        private System.Threading.SendOrPostCallback GetConnectionOperationCompleted;

        /// <remarks/>
        public GetDefault()
        {
            String urlSetting = System.Configuration.ConfigurationManager.AppSettings["GetDefaultWSURL"];
            if (String.IsNullOrEmpty(urlSetting))
                this.Url = "http://demo1.w4vn.com/GetDefault.asmx";
            else
                this.Url = urlSetting;
        }

        /// <remarks/>
        public event GetDefaultLineInfoCompletedEventHandler GetDefaultLineInfoCompleted;

        /// <remarks/>
        public event GetDefaultBPCompletedEventHandler GetDefaultBPCompleted;

        /// <remarks/>
        public event GetPromotionCompletedEventHandler GetPromotionCompleted;

        /// <remarks/>
        public event GetCopyFromToCompletedEventHandler GetCopyFromToCompleted;

        /// <remarks/>
        public event GetConnectionCompletedEventHandler GetConnectionCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDefaultLineInfo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDefaultLineInfo(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate)
        {
            object[] results = this.Invoke("GetDefaultLineInfo", new object[] {
                    UserID,
                    cardCode,
                    itemCode,
                    Quantity,
                    refDate});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDefaultLineInfo(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDefaultLineInfo", new object[] {
                    UserID,
                    cardCode,
                    itemCode,
                    Quantity,
                    refDate}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetDefaultLineInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetDefaultLineInfoAsync(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate)
        {
            this.GetDefaultLineInfoAsync(UserID, cardCode, itemCode, Quantity, refDate, null);
        }

        /// <remarks/>
        public void GetDefaultLineInfoAsync(string UserID, string cardCode, string itemCode, double Quantity, System.DateTime refDate, object userState)
        {
            if ((this.GetDefaultLineInfoOperationCompleted == null))
            {
                this.GetDefaultLineInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefaultLineInfoOperationCompleted);
            }
            this.InvokeAsync("GetDefaultLineInfo", new object[] {
                    UserID,
                    cardCode,
                    itemCode,
                    Quantity,
                    refDate}, this.GetDefaultLineInfoOperationCompleted, userState);
        }

        private void OnGetDefaultLineInfoOperationCompleted(object arg)
        {
            if ((this.GetDefaultLineInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefaultLineInfoCompleted(this, new GetDefaultLineInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDefaultBP", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDefaultBP(string UserID, string CardType)
        {
            object[] results = this.Invoke("GetDefaultBP", new object[] {
                    UserID,
                    CardType});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDefaultBP(string UserID, string CardType, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDefaultBP", new object[] {
                    UserID,
                    CardType}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetDefaultBP(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetDefaultBPAsync(string UserID, string CardType)
        {
            this.GetDefaultBPAsync(UserID, CardType, null);
        }

        /// <remarks/>
        public void GetDefaultBPAsync(string UserID, string CardType, object userState)
        {
            if ((this.GetDefaultBPOperationCompleted == null))
            {
                this.GetDefaultBPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDefaultBPOperationCompleted);
            }
            this.InvokeAsync("GetDefaultBP", new object[] {
                    UserID,
                    CardType}, this.GetDefaultBPOperationCompleted, userState);
        }

        private void OnGetDefaultBPOperationCompleted(object arg)
        {
            if ((this.GetDefaultBPCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDefaultBPCompleted(this, new GetDefaultBPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPromotion", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPromotion(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount)
        {
            object[] results = this.Invoke("GetPromotion", new object[] {
                    UserID,
                    ItemCode,
                    CardCode,
                    Quantity,
                    DocDate,
                    Amount});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetPromotion(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetPromotion", new object[] {
                    UserID,
                    ItemCode,
                    CardCode,
                    Quantity,
                    DocDate,
                    Amount}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetPromotion(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetPromotionAsync(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount)
        {
            this.GetPromotionAsync(UserID, ItemCode, CardCode, Quantity, DocDate, Amount, null);
        }

        /// <remarks/>
        public void GetPromotionAsync(string UserID, string ItemCode, string CardCode, double Quantity, System.DateTime DocDate, double Amount, object userState)
        {
            if ((this.GetPromotionOperationCompleted == null))
            {
                this.GetPromotionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPromotionOperationCompleted);
            }
            this.InvokeAsync("GetPromotion", new object[] {
                    UserID,
                    ItemCode,
                    CardCode,
                    Quantity,
                    DocDate,
                    Amount}, this.GetPromotionOperationCompleted, userState);
        }

        private void OnGetPromotionOperationCompleted(object arg)
        {
            if ((this.GetPromotionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPromotionCompleted(this, new GetPromotionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCopyFromTo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCopyFromTo(int Type, string ObjType)
        {
            object[] results = this.Invoke("GetCopyFromTo", new object[] {
                    Type,
                    ObjType});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetCopyFromTo(int Type, string ObjType, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetCopyFromTo", new object[] {
                    Type,
                    ObjType}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndGetCopyFromTo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void GetCopyFromToAsync(int Type, string ObjType)
        {
            this.GetCopyFromToAsync(Type, ObjType, null);
        }

        /// <remarks/>
        public void GetCopyFromToAsync(int Type, string ObjType, object userState)
        {
            if ((this.GetCopyFromToOperationCompleted == null))
            {
                this.GetCopyFromToOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCopyFromToOperationCompleted);
            }
            this.InvokeAsync("GetCopyFromTo", new object[] {
                    Type,
                    ObjType}, this.GetCopyFromToOperationCompleted, userState);
        }

        private void OnGetCopyFromToOperationCompleted(object arg)
        {
            if ((this.GetCopyFromToCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCopyFromToCompleted(this, new GetCopyFromToCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConnection", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetConnection()
        {
            object[] results = this.Invoke("GetConnection", new object[0]);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetConnection(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetConnection", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public int EndGetConnection(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }

        /// <remarks/>
        public void GetConnectionAsync()
        {
            this.GetConnectionAsync(null);
        }

        /// <remarks/>
        public void GetConnectionAsync(object userState)
        {
            if ((this.GetConnectionOperationCompleted == null))
            {
                this.GetConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConnectionOperationCompleted);
            }
            this.InvokeAsync("GetConnection", new object[0], this.GetConnectionOperationCompleted, userState);
        }

        private void OnGetConnectionOperationCompleted(object arg)
        {
            if ((this.GetConnectionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConnectionCompleted(this, new GetConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDefaultLineInfoCompletedEventHandler(object sender, GetDefaultLineInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefaultLineInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDefaultLineInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetDefaultBPCompletedEventHandler(object sender, GetDefaultBPCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDefaultBPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDefaultBPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetPromotionCompletedEventHandler(object sender, GetPromotionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPromotionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetPromotionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetCopyFromToCompletedEventHandler(object sender, GetCopyFromToCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCopyFromToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetCopyFromToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void GetConnectionCompletedEventHandler(object sender, GetConnectionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public int Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}