//------------------------------------------------------------------------------
// <auto-generated>
//     This _PrjCode was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the _PrjCode is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP {
    
    
    public partial class login {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to _PrjCode-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// Login1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to _PrjCode-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Login Login1;
    }
}
